# in your terminal, run conda: conda env create -f premise_environment.yaml
# or mamba (faster): mamba env create -f premise_environment.yaml

name: premise_env
channels:
  - romainsacchi
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - premise
  - jupyterlab
  - matplotlib
  - eidl
  - unfold
  - seaborn
  - polyviz